import type { Scene } from "@/types/scene";

// Add your own songs here. Drop the MP3 + album art into /public/audio,
// then add a matching entry to `tracks`. First track in the array plays first.
export const keralaScene: Scene = {
  id: "kerala-backwaters",
  name: "Kerala Backwaters",
  label: "Kerala",
  backgroundImage: "/scenes/kerala-scene.png",
  titleText: "केरल के खेत",
  titleFontClass: "font-title",
  timezone: "Asia/Kolkata",
  timeLabel: "Kerela Time",
  spotifyUrl: "https://open.spotify.com",
  ytMusicUrl: "https://music.youtube.com",
  tracks: [
    {
      id: "river-bird",
      title: "River Bird",
      artist: "Pawan Krishna",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/river-bird.mp3",
    },
    {
      id: "drizzle",
      title: "Drizzle",
      artist: "Unknown Artist",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/drizzle.mp3",
    },
    {
      id: "mera-desh",
      title: "Mera Desh",
      artist: "Pawan Krishna",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/mera-desh.mp3",
    },
    {
      id: "hope-dreamcatcher",
      title: "Hope (Dreamcatcher)",
      artist: "Ketan Mohite",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/hope-dreamcatcher.mp3",
    },
    {
      id: "nilaya",
      title: "Nilaya",
      artist: "Unknown Artist",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/nilaya.mp3",
    },
    {
      id: "sudhar",
      title: "Sudhar",
      artist: "Unknown Artist",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/sudhar.mp3",
    },
    {
      id: "baawariya",
      title: "Baawariya",
      artist: "Maatibaani feat. Shankar Tucker",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/baawariya.mp3",
    },
    {
      id: "i-wanted-to-leave-sitar",
      title: "I Wanted to Leave (Sitar Version)",
      artist: "Unknown Artist",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/i-wanted-to-leave-sitar.mp3",
    },
    {
      id: "gravity",
      title: "Gravity",
      artist: "Unknown Artist",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/gravity.mp3",
    },
    {
      id: "krishnas-dance",
      title: "Krishna's Dance",
      artist: "Unknown Artist",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/krishnas-dance.mp3",
    },
  ],
};

export const greeceScene: Scene = {
  id: "greece-santorini",
  name: "Summers in Greece",
  label: "Greece",
  backgroundImage: "/scenes/greece-scene.png",
  titleText: "Summers in Greece",
  titleFontClass: "font-title-elegant",
  timezone: null,
  timeLabel: "Local Time",
  spotifyUrl: "https://open.spotify.com",
  ytMusicUrl: "https://music.youtube.com",
  tracks: [
    {
      id: "paradise",
      title: "Paradise",
      artist: "Unknown Artist",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/paradise.mp3",
    },
    {
      id: "madiba-riddim",
      title: "Madiba Riddim",
      artist: "Drake",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/madiba-riddim.mp3",
    },
    {
      id: "hell-n-back",
      title: "Hell N Back",
      artist: "Bakar",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/hell-n-back.mp3",
    },
    {
      id: "race-my-mind",
      title: "Race My Mind",
      artist: "Drake",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/race-my-mind.mp3",
    },
    {
      id: "massive",
      title: "Massive",
      artist: "Drake",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/massive.mp3",
    },
    {
      id: "flights-booked",
      title: "Flight's Booked",
      artist: "Drake",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/flights-booked.mp3",
    },
    {
      id: "we-are-the-people",
      title: "We Are The People",
      artist: "Empire of the Sun",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/we-are-the-people.mp3",
    },
    {
      id: "summers-over-interlude",
      title: "Summer's Over Interlude",
      artist: "Drake",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/summers-over-interlude.mp3",
    },
    {
      id: "back-on-74",
      title: "Back On 74",
      artist: "Jungle",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/back-on-74.mp3",
    },
    {
      id: "hold-on-were-going-home",
      title: "Hold On, We're Going Home",
      artist: "Drake feat. Majid Jordan",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/hold-on-were-going-home.mp3",
    },
    {
      id: "adventure-of-a-lifetime",
      title: "Adventure Of A Lifetime",
      artist: "Coldplay",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/adventure-of-a-lifetime.mp3",
    },
    {
      id: "pink-dolphin-sunset",
      title: "Pink Dolphin Sunset",
      artist: "Tory Lanez feat. Tee",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/pink-dolphin-sunset.mp3",
    },
    {
      id: "addicted",
      title: "Addicted",
      artist: "Zerb, The Chainsmokers, Ink",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/addicted.mp3",
    },
    {
      id: "take-my-mind",
      title: "Take My Mind",
      artist: "WizTheMc",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/take-my-mind.mp3",
    },
    {
      id: "the-less-i-know-the-better",
      title: "The Less I Know The Better",
      artist: "Tame Impala",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/the-less-i-know-the-better.mp3",
    },
    {
      id: "the-weight-of-attraction",
      title: "The Weight Of Attraction",
      artist: "Unknown Artist",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/the-weight-of-attraction.mp3",
    },
    {
      id: "were-getting-older",
      title: "We're Getting Older",
      artist: "Unknown Artist",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/were-getting-older.mp3",
    },
    {
      id: "lost",
      title: "Lost",
      artist: "Frank Ocean",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/lost.mp3",
    },
    {
      id: "move",
      title: "Move",
      artist: "Adam Port",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/move.mp3",
    },
    {
      id: "nanana",
      title: "(It Goes Like) Nanana",
      artist: "Peggy Gou",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/nanana.mp3",
    },
    {
      id: "get-it-together",
      title: "Get It Together",
      artist: "Drake",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/get-it-together.mp3",
    },
    {
      id: "i-adore-you",
      title: "I Adore You",
      artist: "HUGEL, Topic, Arash ft. Daecolm",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/i-adore-you.mp3",
    },
    {
      id: "the-color-violet",
      title: "The Color Violet",
      artist: "Tory Lanez",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/the-color-violet.mp3",
    },
    {
      id: "passionfruit",
      title: "Passionfruit",
      artist: "Drake",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/passionfruit.mp3",
    },
    {
      id: "coca-white",
      title: "Coca White",
      artist: "Unknown Artist",
      albumArt: "/scenes/greece-scene.png",
      file: "/audio/coca-white.mp3",
    },
  ],
};

export const monacoScene: Scene = {
  id: "monaco",
  name: "Monaco",
  label: "Monaco",
  backgroundImage: "/scenes/monaco-scene.png",
  titleText: "Monaco",
  titleFontClass: "font-title-elegant",
  subtitleText: "(Old money version)",
  timezone: null,
  timeLabel: "Local Time",
  spotifyUrl: "https://open.spotify.com",
  ytMusicUrl: "https://music.youtube.com",
  tracks: [
    {
      id: "bad-bunny-monaco",
      title: "Monaco",
      artist: "Bad Bunny",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/bad-bunny-monaco.mp3",
    },
    {
      id: "she-worships-saturn",
      title: "She Worships Saturn",
      artist: "Viuta",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/she-worships-saturn.mp3",
    },
    {
      id: "its-a-mans-world",
      title: "It's A Man's World",
      artist: "Omar Wilson",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/its-a-mans-world.mp3",
    },
    {
      id: "playground-love",
      title: "Playground Love",
      artist: "feat. Gordon Tracks",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/playground-love.mp3",
    },
    {
      id: "feet-dont-fail-me-now",
      title: "Feet Don't Fail Me Now",
      artist: "Joy Crookes",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/feet-dont-fail-me-now.mp3",
    },
    {
      id: "back-to-black",
      title: "Back To Black",
      artist: "Amy Winehouse",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/back-to-black.mp3",
    },
    {
      id: "like-a-tattoo",
      title: "Like a Tattoo",
      artist: "Sade",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/like-a-tattoo.mp3",
    },
    {
      id: "pearls",
      title: "Pearls",
      artist: "Sade",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/pearls.mp3",
    },
    {
      id: "dualshock",
      title: "Dualshock",
      artist: "Promise",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/dualshock.mp3",
    },
    {
      id: "smooth-operator",
      title: "Smooth Operator",
      artist: "Sade",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/smooth-operator.mp3",
    },
    {
      id: "serenade",
      title: "Serenade",
      artist: "Unknown Artist",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/serenade.mp3",
    },
    {
      id: "missing-todd-terry-club-mix",
      title: "Missing (Todd Terry Club Mix)",
      artist: "Unknown Artist",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/missing-todd-terry-club-mix.mp3",
    },
    {
      id: "lovesong",
      title: "Lovesong",
      artist: "Adele",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/lovesong.mp3",
    },
    {
      id: "la-mentira",
      title: "La Mentira",
      artist: "Luis Miguel",
      albumArt: "/scenes/monaco-scene.png",
      file: "/audio/la-mentira.mp3",
    },
  ],
};

export const grandTetonsScene: Scene = {
  id: "grand-tetons",
  name: "Grand Tetons",
  label: "Grand Tetons",
  backgroundImage: "/scenes/grand-tetons-scene.png",
  titleText: "Grand Tetons",
  titleFontClass: "font-title-elegant",
  timezone: null,
  timeLabel: "Local Time",
  spotifyUrl: "https://open.spotify.com",
  ytMusicUrl: "https://music.youtube.com",
  tracks: [
    {
      id: "placeholder",
      title: "Add your first song",
      artist: "Drop an MP3 in /public/audio",
      albumArt: "/scenes/grand-tetons-scene.png",
      file: "",
    },
  ],
};

// Add new presets here — the switcher UI and scene-transition logic are
// both generic over this array, so a new entry is the only change needed.
export const scenes: Scene[] = [
  keralaScene,
  greeceScene,
  monacoScene,
  grandTetonsScene,
];
