import type { Scene } from "@/types/scene";

// Add your own songs here. Drop the MP3 + album art into /public/audio,
// then add a matching entry to `tracks`. First track in the array plays first.
export const keralaScene: Scene = {
  id: "kerala-backwaters",
  name: "Kerala Backwaters",
  label: "Kerala",
  backgroundImage: "/scenes/kerala-scene.png",
  titleText: "केरल के खेत",
  titleFontClass: "font-title",
  timezone: "Asia/Kolkata",
  timeLabel: "Kerela Time",
  spotifyUrl: "https://open.spotify.com",
  ytMusicUrl: "https://music.youtube.com",
  tracks: [
    {
      id: "river-bird",
      title: "River Bird",
      artist: "Pawan Krishna",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/river-bird.mp3",
    },
    {
      id: "drizzle",
      title: "Drizzle",
      artist: "Unknown Artist",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/drizzle.mp3",
    },
    {
      id: "mera-desh",
      title: "Mera Desh",
      artist: "Pawan Krishna",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/mera-desh.mp3",
    },
    {
      id: "hope-dreamcatcher",
      title: "Hope (Dreamcatcher)",
      artist: "Ketan Mohite",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/hope-dreamcatcher.mp3",
    },
    {
      id: "nilaya",
      title: "Nilaya",
      artist: "Unknown Artist",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/nilaya.mp3",
    },
    {
      id: "sudhar",
      title: "Sudhar",
      artist: "Unknown Artist",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/sudhar.mp3",
    },
    {
      id: "baawariya",
      title: "Baawariya",
      artist: "Maatibaani feat. Shankar Tucker",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/baawariya.mp3",
    },
    {
      id: "i-wanted-to-leave-sitar",
      title: "I Wanted to Leave (Sitar Version)",
      artist: "Unknown Artist",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/i-wanted-to-leave-sitar.mp3",
    },
    {
      id: "gravity",
      title: "Gravity",
      artist: "Unknown Artist",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/gravity.mp3",
    },
    {
      id: "krishnas-dance",
      title: "Krishna's Dance",
      artist: "Unknown Artist",
      albumArt: "/scenes/kerala-scene.png",
      file: "/audio/krishnas-dance.mp3",
    },
  ],
};

export const summerScene: Scene = {
  id: "summer-coast",
  name: "Summer Coast",
  label: "Summer",
  backgroundImage: "/scenes/summer-scene.png",
  titleText: "Summer",
  titleFontClass: "font-title",
  timezone: null,
  timeLabel: "Local Time",
  spotifyUrl: "https://open.spotify.com",
  ytMusicUrl: "https://music.youtube.com",
  tracks: [
    {
      id: "paradise",
      title: "Paradise",
      artist: "Unknown Artist",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/paradise.mp3",
    },
    {
      id: "madiba-riddim",
      title: "Madiba Riddim",
      artist: "Drake",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/madiba-riddim.mp3",
    },
    {
      id: "hell-n-back",
      title: "Hell N Back",
      artist: "Bakar",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/hell-n-back.mp3",
    },
    {
      id: "race-my-mind",
      title: "Race My Mind",
      artist: "Drake",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/race-my-mind.mp3",
    },
    {
      id: "massive",
      title: "Massive",
      artist: "Drake",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/massive.mp3",
    },
    {
      id: "flights-booked",
      title: "Flight's Booked",
      artist: "Drake",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/flights-booked.mp3",
    },
    {
      id: "we-are-the-people",
      title: "We Are The People",
      artist: "Empire of the Sun",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/we-are-the-people.mp3",
    },
    {
      id: "summers-over-interlude",
      title: "Summer's Over Interlude",
      artist: "Drake",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/summers-over-interlude.mp3",
    },
    {
      id: "back-on-74",
      title: "Back On 74",
      artist: "Jungle",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/back-on-74.mp3",
    },
    {
      id: "hold-on-were-going-home",
      title: "Hold On, We're Going Home",
      artist: "Drake feat. Majid Jordan",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/hold-on-were-going-home.mp3",
    },
    {
      id: "adventure-of-a-lifetime",
      title: "Adventure Of A Lifetime",
      artist: "Coldplay",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/adventure-of-a-lifetime.mp3",
    },
    {
      id: "pink-dolphin-sunset",
      title: "Pink Dolphin Sunset",
      artist: "Tory Lanez feat. Tee",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/pink-dolphin-sunset.mp3",
    },
    {
      id: "addicted",
      title: "Addicted",
      artist: "Zerb, The Chainsmokers, Ink",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/addicted.mp3",
    },
    {
      id: "take-my-mind",
      title: "Take My Mind",
      artist: "WizTheMc",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/take-my-mind.mp3",
    },
    {
      id: "the-less-i-know-the-better",
      title: "The Less I Know The Better",
      artist: "Tame Impala",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/the-less-i-know-the-better.mp3",
    },
    {
      id: "the-weight-of-attraction",
      title: "The Weight Of Attraction",
      artist: "Unknown Artist",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/the-weight-of-attraction.mp3",
    },
    {
      id: "were-getting-older",
      title: "We're Getting Older",
      artist: "Unknown Artist",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/were-getting-older.mp3",
    },
    {
      id: "lost",
      title: "Lost",
      artist: "Frank Ocean",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/lost.mp3",
    },
    {
      id: "move",
      title: "Move",
      artist: "Adam Port",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/move.mp3",
    },
    {
      id: "nanana",
      title: "(It Goes Like) Nanana",
      artist: "Peggy Gou",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/nanana.mp3",
    },
    {
      id: "get-it-together",
      title: "Get It Together",
      artist: "Drake",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/get-it-together.mp3",
    },
    {
      id: "i-adore-you",
      title: "I Adore You",
      artist: "HUGEL, Topic, Arash ft. Daecolm",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/i-adore-you.mp3",
    },
    {
      id: "the-color-violet",
      title: "The Color Violet",
      artist: "Tory Lanez",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/the-color-violet.mp3",
    },
    {
      id: "passionfruit",
      title: "Passionfruit",
      artist: "Drake",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/passionfruit.mp3",
    },
    {
      id: "coca-white",
      title: "Coca White",
      artist: "Unknown Artist",
      albumArt: "/scenes/summer-scene.png",
      file: "/audio/coca-white.mp3",
    },
  ],
};

// Add new presets here — the switcher UI and scene-transition logic are
// both generic over this array, so a new entry is the only change needed.
export const scenes: Scene[] = [keralaScene, summerScene];
